app/main/forms.py
from wtforms import StringField, TextAreaField, SubmitField, MultipleFileField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Email
from flask_wtf.file import FileAllowed

class ContactForm(FlaskForm):
    name_surname = StringField('İsim Soyisim*', validators=[DataRequired()])
    email_address = StringField('E-mail Adresi*', validators=[DataRequired(), Email()])
    subject = StringField('Konu*', validators=[DataRequired()])
    message = TextAreaField('Mesajınız*', validators=[DataRequired()])
    images = MultipleFileField('Görsel(ler)inizi yükleyin', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('GÖNDER')

app/main/routes.py
from email import message
from flask import Blueprint, jsonify, url_for, render_template, request, redirect, flash
from app.models import Content, FormRequests
from app.main.forms import ContactForm
from app import db
from app.admin.utils import save_request_picture


main = Blueprint("main", __name__)

@main.route('/')
@main.route('/home')
def home():
        return render_template("main/home.html", title="Home")


@main.route('/gallery')
def gallery():
    contents = db.session.query(Content)
    return render_template('main/gallery.html', title='Gallery', contents=contents)


@main.route('/about')
def about():
    return render_template('main/about.html',title="About")


@main.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            images = []
            for image in form.images.data:
                saved_image = save_request_picture(image)
                if saved_image:
                    url = url_for('static', filename="images/requests/"+saved_image)
                    images.append(url)
            new_request = FormRequests(name_surname=form.name_surname.data, email_address=form.email_address.data,
                        subject=form.subject.data, message=form.message.data, images=images)
            db.session.add(new_request)
            db.session.commit()
            flash('Mesajınız başarıyla iletildi!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Girdiğiniz verileri kontrol ediniz!', 'danger')
    return render_template('main/contact.html', title="Contact", form=form)

app/templates/main/about.html
{% extends 'main/base.html' %}

{% block container %}
<div class="col-sm-12 col-md-10 mx-auto text-justify mb-5 pb-5">
    <div class="mt-5 mb-5 mx-auto col-sm-12 col-md-10">
        <div class="img-container mx-auto col-12 my-4">
            <img src="{{url_for('static', filename='images/img-5.jpg')}}" alt="" class="responsive img-thumbnail">
        </div>
        <div class="col-12 mb-5 pb-5">
            <p class="mb-5 pb-5">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores magni veniam ab inventore dolor
                repudiandae nam cupiditate asperiores sed dolore architecto illo possimus porro libero voluptatem
                ratione rem, doloribus reprehenderit hic animi. Optio harum quo quos veritatis, dolores, natus,
                reprehenderit accusantium temporibus cumque ducimus sed! Mollitia molestiae ullam eum exercitationem
                asperiores deleniti accusantium suscipit consectetur voluptatibus? Corrupti sit laudantium deserunt
                eveniet provident vitae dignissimos rem, repudiandae adipisci. Quam, voluptatum sunt. Numquam facilis
                est saepe? Fugit, facilis soluta maxime vel necessitatibus corrupti animi amet beatae quod quos nam
                alias ratione. Sunt, odio possimus esse autem non perferendis provident et totam minus.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit temporibus quas illo quaerat nostrum
                ducimus eligendi, velit, earum harum molestias ea. In nisi odio consequuntur laborum illum impedit
                magnam accusantium unde sit officia dolores nam dolorem obcaecati enim eos voluptas dignissimos
                veritatis, corporis quibusdam atque. Soluta blanditiis fuga ut architecto vel aut maiores accusantium
                officia explicabo. Iste quasi possimus minus repellendus architecto sunt? Quos at cupiditate dolorum
                modi accusantium sint non expedita quod, blanditiis id, facere tempore maxime vel laboriosam
                consequuntur mollitia illo voluptatibus voluptatem quae quas, unde ea. Possimus sint at quas ab nobis
                veniam cupiditate nulla, ipsum voluptate.
            </p>
        </div>
    </div>
</div>

{% endblock %}

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="shortcut icon" type="image/x-icon" href="{{url_for('static', filename='images/favicon.ico')}}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,400;1,600;1,700&display=swap"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/index.css')}}">
    {% if title %}
    <title>Ateş İlbaşı Tattoo - {{title}}</title>
    {% else %}
    <title>Ateş İlbaşı Tattoo</title>
    {% endif %}

</head>

<body>
    <header class="container ps-0 d-flex flex-column flex-md-row">
        <div class="mt-4 align-text-bottom col-xs-12 ms-0 d-flex flex-column flex-md-row justify-content-between w-100">
            <ul class="nav">
                <li class="nav-item font-weight-bold text-secondary disabled">
                    <a href="{{url_for('main.home')}}" class="text-secondary">
                        <img class="mr-4" style="width:50px; height:50px;"
                            src="{{url_for('static', filename='images/logo.png')}}" alt="">
                        ATEŞ İLBAŞI TATTOO
                    </a>
                </li>
            </ul>
            <ul class="nav justify-content-start mt-1 d-flex flex-nowrap">
                <li class="nav-item text-secondary">
                    <a {%if title=="Home" %} class="nav-link font-weight-bold disabled border-bottom" {% else %}
                        class="nav-link font-weight-bold text-secondary" href="{{url_for('main.home')}}" {%endif%}><img
                            style="width:18px; height:18px" src="{{url_for('static', filename='images/home.png')}}"></a>
                </li>
                <li class="nav-item text-secondary">
                    <a {%if title=="Gallery" %} class="nav-link font-weight-bold disabled border-bottom" {% else %}
                        class="nav-link font-weight-bold text-secondary" href="{{url_for('main.gallery')}}"
                        {%endif%}>GALERİ</a>
                </li>
                <li class="nav-item  text-secondary">
                    <a {%if title=="About" %} class="nav-link font-weight-bold disabled border-bottom" {% else %}
                        class="nav-link font-weight-bold text-secondary" href="{{url_for('main.about')}}"
                        {%endif%}>HAKKIMDA</a>
                </li>
                <li class="nav-item text-secondary">
                    <a {%if title=="Contact" %} class="nav-link font-weight-bold disabled border-bottom" {% else %}
                        class="nav-link font-weight-bold text-secondary" href="{{url_for('main.contact')}}"
                        {%endif%}>İLETİŞİM</a>
                </li>
            </ul>
        </div>
    </header>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="mt-3 alert alert-{{ category }} alert-dismissible fade show" role="alert" id="flashed_messages">
            {{message}}
            <button type="button" class="close test-white" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>

    {% block container %}{% endblock %}
    <footer class="bg-white">
        <div class="d-flex flex-column">
            <div class="nav d-flex justify-content-center mt-2">
                <a class="nav-item py-sm-0 px-3 py-md-3" href="https://wa.me/+905068100239?lang=tr" target="_blank">
                    <img style="width:50px; height:50px; filter:grayscale(100%)"
                        src="{{url_for('static', filename='images/whatsapp.png')}}" class="footer-logo">
                </a>
                <a class="nav-item py-sm-0 px-3 py-md-3" href="#">
                    <img style="width:50px; height:50px" src="{{url_for('static', filename='images/instagram.png')}}"
                        class="footer-logo">
                </a>
            </div>
            <ul class="nav d-flex justify-content-center my-2 text-secondary">
                <li class="nav-item">
                    Designed & Coded by KP Design
                </li>
            </ul>
        </div>
    </footer>
    <script src="{{url_for('static', filename='script/jquery.js')}}"></script>
    <script src="{{url_for('static', filename='script/index.js')}}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

app/templates/main/contact.html
{% extends 'main/base.html' %}

{% block container %}

<div class="container my-5 p-5 pt-0 text-secondary">
  <h2 class="fw-bold my-5">MESAJ GÖNDER</h2>
  <p class="mb-5">Dövmelerle alakalı soru sormak, bilgi almak, dövme randevusu almak istiyorsan bana yazabilirsin. En
    geç 2 iş günü içerisinde dönüş yapmaya çalışacağım.</p>
  <form class="row mb-5" enctype="multipart/form-data" method="POST" action="">
    {{form.hidden_tag()}}
    <div class="col-md-6 mb-3">
      {{form.name_surname.label(class="form-label fw-bold")}}
      {{form.name_surname(class="form-control", placeholder='Lütfen isminizi giriniz.')}}
    </div>
    <div class="col-md-6 mb-3">
      {{form.email_address.label(class="form-label fw-bold")}}
      {{form.email_address(class="form-control", placeholder='Lütfen e-mail adresinizi yazınız.')}}
    </div>
    <div class="col-12 mb-3">
      {{form.subject.label(class="form-label fw-bold")}}
      {{form.subject(class="form-control", placeholder='Lütfen mesajın konusunu yazınız.')}}
    </div>
    <div class="col-12 mb-3">
      {{form.message.label(class="form-label fw-bold")}}
      {{form.message(class="form-control", placeholder='Lütfen mesajınızı yazınız.')}}
    </div>
    <div class="col-12 mb-3">
      {{form.images(class="form-control", style="display:none")}}
      {{form.images.label(class="form-label font-weight-bold btn btn-secondary col-sm-12")}}
      <div id="file-container">

      </div>
    </div>
    <div class="col-12 text-center mb-5">
      {{form.submit(class="btn btn-secondary fw-bold")}}
    </div>
  </form>
</div>


{% endblock %}

app/templates/main/gallery.html
{% extends 'main/base.html' %}

{% block container %}
<div class="mb-5 pb-5">
    <div class="container-fluid d-flex flex-wrap justify-sm-content-center pb-5  mb-5">
      {% for content in contents %}
      <div class="img-container col-sm-8 col-md-6 col-lg-4 col-xl-3 my-5 text-center">
        <img src="{{content.image}}" alt="" class="img-thumbnail responsive">
      </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/main/home.html
{% extends 'main/base.html' %}
{% block container %}
<div class="c-12" id="gif-container">
    <img src="{{url_for('static', filename='images/home.gif')}}" alt="" class="img-thumbnail">
</div>


{% endblock %}